# Generated by Django 5.1.2 on 2025-05-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ammunition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.CharField(max_length=50)),
                ("encumbrance", models.IntegerField()),
                ("availability", models.CharField(max_length=50)),
                ("range", models.CharField(max_length=50)),
                ("damage", models.CharField(max_length=50)),
                ("qualities_and_flaws", models.CharField(max_length=200)),
                ("type", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="AnimalsAndVehicles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.CharField(max_length=50)),
                ("encumbrance", models.IntegerField()),
                ("carries", models.IntegerField()),
                ("availability", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Armour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.CharField(max_length=50)),
                ("encumbrance", models.IntegerField()),
                ("availability", models.CharField(max_length=50)),
                ("penalty", models.CharField(max_length=50)),
                ("locations", models.CharField(max_length=50)),
                ("aps", models.IntegerField()),
                ("qualities_and_flaws", models.CharField(max_length=200)),
                ("type", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="BooksAndDocuments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.CharField(max_length=50)),
                ("encumbrance", models.IntegerField()),
                ("availability", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="ClothingAndAccessories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.CharField(max_length=50)),
                ("encumbrance", models.IntegerField()),
                ("availability", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="DrugsAndPoisons",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.CharField(max_length=50)),
                ("encumbrance", models.IntegerField()),
                ("availability", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="FoodDrinkAndLodging",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.CharField(max_length=50)),
                ("encumbrance", models.IntegerField()),
                ("availability", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="HerbsAndDraughts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.CharField(max_length=50)),
                ("encumbrance", models.IntegerField()),
                ("availability", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Hirelings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("quick_job", models.CharField(max_length=50)),
                ("daily_cost", models.CharField(max_length=50)),
                ("weekly_cost", models.CharField(max_length=50)),
                ("notes", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="MeleeWeapons",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.CharField(max_length=50)),
                ("encumbrance", models.IntegerField()),
                ("availability", models.CharField(max_length=50)),
                ("reach", models.CharField(max_length=50)),
                ("damage", models.CharField(max_length=50)),
                ("qualities_and_flaws", models.CharField(max_length=200)),
                ("type", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="MiscellaneousTrappings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.CharField(max_length=50)),
                ("encumbrance", models.IntegerField()),
                ("availability", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="PacksAndContainers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.CharField(max_length=50)),
                ("encumbrance", models.IntegerField()),
                ("carries", models.IntegerField()),
                ("availability", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Prosthetics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.CharField(max_length=50)),
                ("encumbrance", models.IntegerField()),
                ("availability", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="RangedWeapons",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.CharField(max_length=50)),
                ("encumbrance", models.IntegerField()),
                ("availability", models.CharField(max_length=50)),
                ("range", models.CharField(max_length=50)),
                ("damage", models.CharField(max_length=50)),
                ("qualities_and_flaws", models.CharField(max_length=200)),
                ("type", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="ToolsAndKits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.CharField(max_length=50)),
                ("encumbrance", models.IntegerField()),
                ("availability", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="TradeToolsAndWorkshops",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("price", models.CharField(max_length=50)),
                ("encumbrance", models.IntegerField()),
                ("availability", models.CharField(max_length=50)),
            ],
        ),
    ]
