# Generated by Django 5.2.3 on 2025-06-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_alter_characters_career_tier_and_more'),
        ('equipment', '0003_charactermeleeweapons_unique_melee_weapon_per_character'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='characterammunition',
            constraint=models.UniqueConstraint(fields=('character', 'ammunition'), name='unique_ammunition_per_character'),
        ),
        migrations.AddConstraint(
            model_name='characterarmour',
            constraint=models.UniqueConstraint(fields=('character', 'armour'), name='unique_armour_per_character'),
        ),
        migrations.AddConstraint(
            model_name='characterclothingandaccessories',
            constraint=models.UniqueConstraint(fields=('character', 'clothing_and_accessories'), name='unique_clothing_and_accessories_per_character'),
        ),
        migrations.AddConstraint(
            model_name='characterpacksandcontainers',
            constraint=models.UniqueConstraint(fields=('character', 'packs_and_containers'), name='unique_packs_and_containers_per_character'),
        ),
        migrations.AddConstraint(
            model_name='characterrangedweapons',
            constraint=models.UniqueConstraint(fields=('character', 'ranged_weapon'), name='unique_ranged_weapon_per_character'),
        ),
    ]
