# Generated by Django 5.2.3 on 2025-07-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0007_alter_characters_career_tier_and_more'),
        ('equipment', '0004_characterammunition_unique_ammunition_per_character_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='characterfooddrinkandlodging',
            constraint=models.UniqueConstraint(fields=('character', 'food_drink_and_lodging'), name='unique_food_drink_and_lodging_per_character'),
        ),
        migrations.AddConstraint(
            model_name='charactertoolsandkits',
            constraint=models.UniqueConstraint(fields=('character', 'tools_and_kits'), name='unique_tools_and_kits_per_character'),
        ),
    ]
