# Generated by Django 5.1.2 on 2025-01-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0002_characteristics_ag_advances_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="advancedskills",
            old_name="advances",
            new_name="advances_0",
        ),
        migrations.RenameField(
            model_name="advancedskills",
            old_name="attribute_name",
            new_name="attribute_name_0",
        ),
        migrations.RenameField(
            model_name="advancedskills",
            old_name="attribute_value",
            new_name="attribute_value_0",
        ),
        migrations.RenameField(
            model_name="advancedskills",
            old_name="name",
            new_name="name_0",
        ),
        migrations.RenameField(
            model_name="advancedskills",
            old_name="sum",
            new_name="total_0",
        ),
        migrations.AddField(
            model_name="advancedskills",
            name="advances_1",
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="advancedskills",
            name="advances_2",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="advancedskills",
            name="attribute_name_1",
            field=models.CharField(default=2, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="advancedskills",
            name="attribute_name_2",
            field=models.CharField(default=2, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="advancedskills",
            name="attribute_value_1",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="advancedskills",
            name="attribute_value_2",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="advancedskills",
            name="name_1",
            field=models.CharField(default=2, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="advancedskills",
            name="name_2",
            field=models.CharField(default=2, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="advancedskills",
            name="total_1",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="advancedskills",
            name="total_2",
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
