# Generated by Django 5.1.2 on 2025-01-24 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0003_rename_advances_advancedskills_advances_0_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="advancedskills",
            old_name="advances_0",
            new_name="advances",
        ),
        migrations.RenameField(
            model_name="advancedskills",
            old_name="attribute_name_0",
            new_name="attribute_name",
        ),
        migrations.RenameField(
            model_name="advancedskills",
            old_name="attribute_value_0",
            new_name="attribute_value",
        ),
        migrations.RenameField(
            model_name="advancedskills",
            old_name="name_0",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="advancedskills",
            old_name="total_0",
            new_name="total",
        ),
        migrations.RemoveField(
            model_name="advancedskills",
            name="advances_1",
        ),
        migrations.RemoveField(
            model_name="advancedskills",
            name="advances_2",
        ),
        migrations.RemoveField(
            model_name="advancedskills",
            name="attribute_name_1",
        ),
        migrations.RemoveField(
            model_name="advancedskills",
            name="attribute_name_2",
        ),
        migrations.RemoveField(
            model_name="advancedskills",
            name="attribute_value_1",
        ),
        migrations.RemoveField(
            model_name="advancedskills",
            name="attribute_value_2",
        ),
        migrations.RemoveField(
            model_name="advancedskills",
            name="name_1",
        ),
        migrations.RemoveField(
            model_name="advancedskills",
            name="name_2",
        ),
        migrations.RemoveField(
            model_name="advancedskills",
            name="total_1",
        ),
        migrations.RemoveField(
            model_name="advancedskills",
            name="total_2",
        ),
    ]
