# Generated by Django 5.1.2 on 2025-03-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0004_rename_advances_0_advancedskills_advances_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characters",
            name="species",
            field=models.CharField(
                choices=[
                    ("Human", "Human"),
                    ("Dwarf", "Dwarf"),
                    ("Halfling", "Halfling"),
                    ("Wood Elf", "Wood Elf"),
                    ("High Elf", "High Elf"),
                ],
                default="Human",
                max_length=100,
            ),
        ),
    ]
