# Generated by Django 5.1.2 on 2025-03-20 12:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0005_alter_characters_species"),
    ]

    operations = [
        migrations.AddField(
            model_name="characters",
            name="backstory",
            field=models.CharField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="characters",
            name="other_information",
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wounds",
            name="current_wounds",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="characters",
            name="species",
            field=models.CharField(
                choices=[
                    ("Human", "Human"),
                    ("Dwarf", "Dwarf"),
                    ("Halfling", "Halfling"),
                    ("Wood Elf", "Wood Elf"),
                    ("High Elf", "High Elf"),
                ],
                max_length=100,
            ),
        ),
    ]
