# Generated by Django 5.1.2 on 2025-05-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "characters",
            "0006_characters_backstory_characters_other_information_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="characters",
            name="career_tier",
            field=models.CharField(
                choices=[("1", "1"), ("2", "2"), ("3", "3"), ("4", "4")],
                default="1",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="characters",
            name="species",
            field=models.CharField(
                choices=[
                    ("Human", "Human"),
                    ("Dwarf", "Dwarf"),
                    ("Halfling", "Halfling"),
                    ("Wood Elf", "Wood Elf"),
                    ("High Elf", "High Elf"),
                ],
                default="Human",
                max_length=100,
            ),
        ),
    ]
